on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request: 
    branches:
      - main

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/flask-microservice

jobs:
  # Download repo, setup python, setup dependencies, and run pytest.
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      # This downloads the repo onto Github Actions runner.
      - name: Checkout code
        uses: actions/checkout@v4

      # This download and setup python.
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # '|' is YAML syntax indicator which treats everything indented below as a single multi-line string
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest-cov

      # Run pytest
      - name: Run tests with coverage
        run: |
          python -m pytest tests/ -v \
            --cov=app \
            --cov-report=term-missing \
            --cov-fail-under=80

  # Every push to main will create docker image
  build-and-push:
    name: Build and Push Image
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push'

    # outputs block is how you pass data from one job to another 
    outputs:
      image-tag:    ${{ steps.meta.outputs.tags }}
      image-digest: ${{ steps.build.outputs.digest }}
      version:      ${{ steps.version.outputs.version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # jobs are referenced by their name, steps by their id
      - name: Determine version
        id: version
        run: |
          if [[ "${{ github.ref }}" == refs/tags/v* ]]; then
            VERSION="${{ github.ref_name }}"
          else
            VERSION="sha-$(echo ${{ github.sha }} | cut -c1-7)"
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Version: $VERSION"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha,prefix=sha-
        
      - name: Build and push image
        id: build
        uses: docker/build-push-action@v5
        with:
          context:   .
          push:      true
          tags:      ${{ steps.meta.outputs.tags }}
          labels:    ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to:   type=gha,mode=max

  scan:
    name: Security Scan
    runs-on: ubuntu-latest
    needs: build-and-push
    if: github.event_name == 'push'

    steps:
      # Trivy is vulnerability scanner against Common Vulnerabilities and Exposures (CVEs)
      - name: Run Trivy vulnerability scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref:    "${{ env.IMAGE_NAME }}:main"
          format:       "table"
          exit-code:    "0"
          severity:     "CRITICAL,HIGH"
          ignore-unfixed: true

  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    needs: scan
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      
      - name: Checkout code
        uses: actions/checkout@v4

      # Temporarily setup so Github Actions runner can SSH into EC2 instance and do the rest of works.
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/deploy_key.pem
          chmod 600 ~/.ssh/deploy_key.pem
          # skip the SSH prompt, because no one to type YES
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Copy deploy files to EC2
        run: |
          scp -i ~/.ssh/deploy_key.pem \
            docker-compose.prod.yml \
            scripts/deploy.sh \
            scripts/push_health_metric.py \
            ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/ubuntu/flask-microservice/

      - name: Run deploy script on EC2
        run: |
          ssh -i ~/.ssh/deploy_key.pem \
            ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} \
            "bash /home/ubuntu/flask-microservice/deploy.sh \
              ${{ env.IMAGE_NAME }}:main \
              ${{ needs.build-and-push.outputs.version }}"